using System;
using System.ComponentModel;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace WaaS.Generators;

[Generator(LanguageNames.CSharp)]
public class ComponentBindingFormatterGenerator : IIncrementalGenerator
{
    private enum FormatterKind
    {
        Record,
        Variant,
        Alias
    }

    private static SymbolDisplayFormat ForTypeDeclaration = new(
        SymbolDisplayGlobalNamespaceStyle.Omitted,
        SymbolDisplayTypeQualificationStyle.NameOnly,
        SymbolDisplayFormat.FullyQualifiedFormat.GenericsOptions,
        SymbolDisplayFormat.FullyQualifiedFormat.MemberOptions,
        SymbolDisplayFormat.FullyQualifiedFormat.DelegateStyle,
        SymbolDisplayFormat.FullyQualifiedFormat.ExtensionMethodStyle,
        SymbolDisplayFormat.FullyQualifiedFormat.ParameterOptions,
        SymbolDisplayFormat.FullyQualifiedFormat.PropertyStyle,
        SymbolDisplayFormat.FullyQualifiedFormat.LocalOptions,
        SymbolDisplayFormat.FullyQualifiedFormat.KindOptions,
        SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
    );


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                $"WaaS.ComponentModel.Binding.ComponentRecordAttribute",
                static (node, ct) => true,
                (context, ct) => context);

            context.RegisterSourceOutput(source,
                (source, context) => EmitFormatter(source, context, FormatterKind.Record));
        }
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                $"WaaS.ComponentModel.Binding.ComponentVariantAttribute",
                static (node, ct) => true,
                (context, ct) => context);

            context.RegisterSourceOutput(source,
                (source, context) => EmitFormatter(source, context, FormatterKind.Variant));
        }
        {
            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                $"WaaS.ComponentModel.Binding.ComponentAliasAttribute",
                static (node, ct) => true,
                (context, ct) => context);

            context.RegisterSourceOutput(source,
                (source, context) => EmitFormatter(source, context, FormatterKind.Alias));
        }
    }

    private void EmitFormatter(SourceProductionContext source, GeneratorAttributeSyntaxContext context,
        FormatterKind kind)
    {
        StringBuilder sourceBuilder = new();

        var symbol = context.TargetSymbol;

        if (symbol is not INamedTypeSymbol namedSymbol) return;

        var identifier = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
            .WithGenericsOptions(SymbolDisplayGenericsOptions.None));
        if (namedSymbol.Arity > 0) identifier += $"`{namedSymbol.Arity}";

        sourceBuilder.AppendLine(
/* lang=c#  */"""
              // <auto-generated />
              #nullable enable
              using System;
              """);

        // TODO: nested class check

        if (!namedSymbol.ContainingNamespace.IsGlobalNamespace)
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                  namespace {{namedSymbol.ContainingNamespace}}
                  {
                  """);

        // nested types

        static void PrintNestedTypeOpeners(StringBuilder sourceBuilder, INamedTypeSymbol symbol)
        {
            var containingSymbol = symbol.ContainingSymbol;
            if (containingSymbol is INamedTypeSymbol namedSymbol)
            {
                PrintNestedTypeOpeners(sourceBuilder, namedSymbol);
            }

            var kind = symbol.TypeKind switch
            {
                TypeKind.Class => "class",
                TypeKind.Interface => "interface",
                TypeKind.Struct => "struct",
                _ => throw new ArgumentOutOfRangeException()
            };
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                  partial {{kind}} {{symbol.ToDisplayString(ForTypeDeclaration)}}
                  {
                  """);
        }

        if (namedSymbol.ContainingSymbol is INamedTypeSymbol containingSymbol)
            PrintNestedTypeOpeners(sourceBuilder, containingSymbol);

        var name = namedSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // TODO: generics
        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                    partial {{namedSymbol.TypeKind switch {
                        TypeKind.Class => "class",
                        TypeKind.Struct => "struct"
                    }}} {{namedSymbol.ToDisplayString(ForTypeDeclaration)}}
                    {
                        static {{namedSymbol.Name}}()
                        {
                            global::WaaS.ComponentModel.Binding.FormatterProvider.Register<{{name}}>(new __GeneratedFormatter());
                            StaticConstructor();
                        }
                        
                        static partial void StaticConstructor();
                
                        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                        private class __GeneratedFormatter : global::WaaS.ComponentModel.Binding.IFormatter<{{name}}>
                        {
                """);

        switch (kind)
        {
            case FormatterKind.Record:
                EmitRecordFormatterBody(namedSymbol, sourceBuilder);
                break;
            case FormatterKind.Variant:
                EmitVariantFormatterBody(namedSymbol, sourceBuilder);
                break;
            case FormatterKind.Alias:
                EmitAliasFormatterBody(namedSymbol, sourceBuilder);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(kind), kind, null);
        }


        sourceBuilder.AppendLine(
/* lang=c#    */"""
                        }
                """);

        if (kind == FormatterKind.Variant)
        {
            sourceBuilder.AppendLine(
/* lang=c#    */"""
                        public int CaseIndex { get; init; }
                """);
        }

        sourceBuilder.AppendLine(
/* lang=c#    */"""
                    }
                """);

        static void PrintNestedTypeClosers(StringBuilder sourceBuilder, INamedTypeSymbol symbol)
        {
            var kind = symbol.TypeKind switch
            {
                TypeKind.Class => "class",
                TypeKind.Interface => "interface",
                TypeKind.Struct => "struct",
                _ => throw new ArgumentOutOfRangeException()
            };
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                  } // partial {{kind}} {{symbol.ToDisplayString(ForTypeDeclaration)}}
                  """);
            var containingSymbol = symbol.ContainingSymbol;
            if (containingSymbol is INamedTypeSymbol namedSymbol)
            {
                PrintNestedTypeOpeners(sourceBuilder, namedSymbol);
            }
        }

        if (namedSymbol.ContainingSymbol is INamedTypeSymbol containingSymbol1)
            PrintNestedTypeClosers(sourceBuilder, containingSymbol1);

        if (!namedSymbol.ContainingNamespace.IsGlobalNamespace)
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                  } // namespace {{namedSymbol.ContainingNamespace}}
                  """);


        source.AddSource($"{identifier}.Formatter.g.cs", sourceBuilder.ToString());
    }

    private static ITypeSymbol GetMemberType(ISymbol member)
    {
        return member switch
        {
            IFieldSymbol field => field.Type,
            IPropertySymbol property => property.Type,
        };
    }

    private static bool TryGetNullableElement(ITypeSymbol symbol, out ITypeSymbol? elementType)
    {
        elementType = default;
        if (symbol is not INamedTypeSymbol { IsGenericType: true } namedTypeSymbol) return false;

        if (!namedTypeSymbol.ConstructUnboundGenericType().Matches("System.Nullable`1")) return false;

        elementType = namedTypeSymbol.TypeArguments[0];
        return true;
    }

    private static void EmitRecordFormatterBody(INamedTypeSymbol namedSymbol, StringBuilder sourceBuilder)
    {
        var name = namedSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var members = namedSymbol.GetMembers()
            .Where(member =>
            {
                return member.DeclaredAccessibility == Accessibility.Public &&
                       !member.IsStatic &&
                       member.GetAttributes().Select(attr => attr.AttributeClass).WhereNotNull().Any(attr =>
                           attr.Matches("WaaS.ComponentModel.Binding.ComponentFieldAttribute"));
            });

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                            public global::WaaS.ComponentModel.Runtime.IValueType Type { get; } = new global::WaaS.ComponentModel.Models.ResolvedRecordType(
                                new global::WaaS.ComponentModel.Models.ResolvedRecordField[]
                                {
                """);
        foreach (var member in members)
        {
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                                      new global::WaaS.ComponentModel.Models.ResolvedRecordField(@"{{Utils.ToComponentApiName(member)}}", global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{{GetMemberType(member).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>().Type),
                  """);
        }

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                });
                """);

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                            public async global::System.Threading.Tasks.ValueTask<{{name}}> PullAsync(global::WaaS.ComponentModel.Binding.Pullable pullable)
                            {
                                var prelude = await pullable.PullPrimitiveValueAsync<global::WaaS.ComponentModel.Binding.RecordPrelude>();
                                pullable = prelude.BodyPullable;
                                
                                return new {{name}}()
                                {
                """);

        // TODO: pull directly for primitive types 
        foreach (var member in members)
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                                      {{member.Name}} = await pullable.PullValueAsync<{{GetMemberType(member).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>(),
                  """);

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                };
                            }
                                
                            public void Push({{name}} value, global::WaaS.ComponentModel.Runtime.ValuePusher pusher)
                            {
                                pusher = pusher.PushRecord();
                """);

        foreach (var member in members)
            sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{{GetMemberType(member).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>().Push(value.{{member.Name}}, pusher);
                """);

        sourceBuilder.AppendLine(
/* lang=c#  */"""
                          }
              """);
    }

    private static void EmitVariantFormatterBody(INamedTypeSymbol namedSymbol, StringBuilder sourceBuilder)
    {
        var name = namedSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var members = namedSymbol.GetMembers()
            .Where(member =>
            {
                return member.DeclaredAccessibility == Accessibility.Public &&
                       !member.IsStatic &&
                       member.GetAttributes().Select(attr => attr.AttributeClass).WhereNotNull().Any(attr =>
                           attr.Matches("WaaS.ComponentModel.Binding.ComponentCaseAttribute"));
            }).ToArray();

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                            public global::WaaS.ComponentModel.Runtime.IValueType Type { get; } = new global::WaaS.ComponentModel.Models.ResolvedVariantType(
                                new global::WaaS.ComponentModel.Models.ResolvedVariantCase[]
                                {
                """);
        foreach (var member in members)
        {
            var memberType = GetMemberType(member);
            var isNone = TryGetNullableElement(memberType, out var elementType) &&
                         elementType!.Matches("WaaS.ComponentModel.Binding.None");
            var typeExpression = isNone
                ? "null"
                : $"global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>().Type";
            sourceBuilder.AppendLine(
                /* lang=c#  */
                $$"""
                                      new global::WaaS.ComponentModel.Models.ResolvedVariantCase(@"{{Utils.ToComponentApiName(member)}}", {{typeExpression}}),
                  """);
        }

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                });
                """);

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                            public async global::System.Threading.Tasks.ValueTask<{{name}}> PullAsync(global::WaaS.ComponentModel.Binding.Pullable pullable)
                            {
                                var prelude = await pullable.PullPrimitiveValueAsync<global::WaaS.ComponentModel.Binding.VariantPrelude>();
                                pullable = prelude.BodyPullable;
                                
                                return prelude.CaseIndex switch
                                {
                """);

        // TODO: pull directly for primitive types 
        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var memberType = GetMemberType(member);
            var isNone = TryGetNullableElement(memberType, out var elementType) &&
                         elementType!.Matches("WaaS.ComponentModel.Binding.None");
            var valueExpression = isNone
                ? "default(global::WaaS.ComponentModel.Binding.None)"
                : $"await pullable.PullValueAsync<{GetMemberType(member).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()";

            sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                    {{i}} => new {{name}}() { CaseIndex = {{i}}, {{member.Name}} = {{valueExpression}} },
                """);
        }

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                    _ => throw new global::System.IndexOutOfRangeException()
                                };
                            }
                                
                            public void Push({{name}} value, global::WaaS.ComponentModel.Runtime.ValuePusher pusher)
                            {
                                pusher = pusher.PushVariant(value.CaseIndex);
                                switch (value.CaseIndex)
                                {
                """);

        for (var i = 0; i < members.Length; i++)
        {
            var member = members[i];
            var memberType = GetMemberType(member);
            var isNone = TryGetNullableElement(memberType, out var elementType) &&
                         elementType!.Matches("WaaS.ComponentModel.Binding.None");
            sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                    case {{i}}:
                """);
            if (!isNone)
                sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                        global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{{GetMemberType(member).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>().Push(value.{{member.Name}}, pusher);
                """);
            sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                                        break;
                """);
        }

        sourceBuilder.AppendLine(
/* lang=c#    */"""
                                    default:
                                        throw new global::System.IndexOutOfRangeException();
                                }
                            }
                """);
    }

    private static void EmitAliasFormatterBody(INamedTypeSymbol namedSymbol, StringBuilder sourceBuilder)
    {
        var name = namedSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var targetType = namedSymbol.GetAttributes()
            .First(attr => attr.AttributeClass.Matches("WaaS.ComponentModel.Binding.ComponentAliasAttribute"))
            .ConstructorArguments[0].Value as ITypeSymbol;

        sourceBuilder.AppendLine(
/* lang=c#  */$$"""
                            public global::WaaS.ComponentModel.Runtime.IValueType Type { get; } = global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{{targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>().Type;
                            public async global::System.Threading.Tasks.ValueTask<{{name}}> PullAsync(global::WaaS.ComponentModel.Binding.Pullable pullable)
                            {
                                return await pullable.PullValueAsync<{{targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>();
                            }
                                
                            public void Push({{name}} value, global::WaaS.ComponentModel.Runtime.ValuePusher pusher)
                            {
                                global::WaaS.ComponentModel.Binding.FormatterProvider.GetFormatter<{{targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}}>().Push(value, pusher);
                            }
                """);
    }
}