// <auto-generated />
#nullable enable

namespace MyGame.MySequencer
{
    // world sequence
    [global::WaaS.ComponentModel.Binding.ComponentInterface(@"sequence")]
    public partial interface ISequence
    {
        [global::WaaS.ComponentModel.Binding.ComponentApi(@"play")]
        global::System.Threading.Tasks.ValueTask Play();

    }
}
