name: Publish Crates

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-crates:
    permissions:
      id-token: write     # Required for OIDC token exchange
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: WaaS/wit2waas
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}