name: Update docs

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: WaaS
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Run docfx
        run: dotnet docfx
      - name: Generate markdown
        run: dotnet run --project DocFxMarkdownGen/DocFxMarkdownGen.csproj
      - name: Restore packages
        run: yarn install
        working-directory: docs
      - name: Deploy
        run: GIT_USER=ruccho yarn deploy
        working-directory: docs